### ISSUE TITLE
Use synthtool for nodejs templating

### ISSUE THREAD

**Issue by JustinBeckwith** [GoogleCloudPlatform/synthtool#10]
In node.js land, we have this problem where we have mostly the same stuff across ~40 repositories (and growing).  I would like to be able to splat a set of templated / generated files into every repo.  

I think synthtool might? be the right way to do that.  Specifically, here are a few things we need:

- [ ] .appveyor.yml
- [x] .circleci/config.yml
- [ ] .eslintignore
- [ ] .eslintrc.yml
- [ ] .github/CONTRIBUTING.md
- [ ] .github/ISSUE_TEMPLATE.md
- [ ] .github/PULL_REQUEST_TEMPLATE.md 
- [ ] .gitignore
- [ ] CODE_OF_CONDUCT.md
- [ ] LICENSE
- [ ] index.js
- ... probably more :)

These files need to support templates with mixins.  For example, I should be able to create a `.gitignore.tpl`  that contains additional ignores I want to add over the default. 

In some cases, we may want to support mixins.  For example - today we generate a `README.md` file using repo-tools that uses basic metadata.  You can see an example of the data file here:
https://github.com/googleapis/nodejs-spanner/blob/master/.cloud-repo-tools.json

And the README it generates here:
https://github.com/googleapis/nodejs-spanner/blob/master/README.md

It's important that we can define mixins for individual portions in the event that we want to add additional information.  For example here's an issue from cloud-debug-nodejs:
https://github.com/GoogleCloudPlatform/nodejs-repo-tools/issues/123

Ideally, we could define:
-  A set of common files that get generated for all repos
- A set of language specific files that get generated

The command that re-generates these files should be run as part of autosynth, or some other periodic tool that performs all of the updates via pull requests that occur automagically after PRs to synthtool with template changes are accepted.

**Comment by JustinBeckwith** [comment]
@crwilcox it looks like we support some sort of templating already :) Can you let us know how close it is to this proposal?

**Comment by crwilcox** [comment]
@JustinBeckwith , .circleci/config.yml is in. The others would need to be templated using jinja style and added to https://github.com/GoogleCloudPlatform/synthtool/tree/master/synthtool/gcp/templates/node_library

**Comment by JustinBeckwith** [comment]
If we want them generated, how do we do it?  Does it happen automatically, or does the user need to modify synth.py?  TL;DR -  please add how to use this to the README :)

**Comment by crwilcox** [comment]
I took some time to add some info to our README. 
https://github.com/GoogleCloudPlatform/synthtool/pull/18

**Comment by JustinBeckwith** [comment]
This is freaking rad @crwilcox

**Comment by crwilcox** [comment]
@theacodes deserves the credit for getting the templating feature written. I just started using it. With a little time we should be able to get all of these templates coming in via synth.py though :)

**Comment by JustinBeckwith** [comment]
I am going to repurpose this issue for adding all this stuff to the nodejs synth.py files.

**Comment by crwilcox** [comment]
https://github.com/GoogleCloudPlatform/synthtool/pull/23 addressing some of the templates needed

**Comment by JustinBeckwith** [comment]
Let's call this done.  We should keep adding new files here as we go :)
