### ISSUE TITLE
Automate addition of new repositories

### ISSUE THREAD

**Issue by JustinBeckwith** [GoogleCloudPlatform/synthtool#13]
Right now we need to go edit a file for autosynth to pick up new repos.  This is error prone, and will lead to us forgetting things.  Lets update autosynth to just run against any repo in in the org that has a `synth.py` in it.

**Comment by theacodes** [comment]
My biggest concern for this is GitHub API quota, but otherwise, should be pretty easy to do.

**Comment by theacodes** [comment]
This is done for Node.js. Other languages can follow suit soon.

**Comment by JustinBeckwith** [comment]
cc @kinwa91 this is awesome
